name: .NET Build & UnitTests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"
    - ".github/workflows/ci.yml"
  pull_request:
    paths:
    - "src/**"
    - ".github/workflows/ci.yml"
  
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: src
  TESTING_DIRECTORY: src
  ApplicationName: ${{ secrets.APPLICATIONNAME }}
  CalendarId: ${{ secrets.CALENDARID }}
  ServiceAccountClientEmail: ${{ secrets.SERVICEACCOUNTCLIENTEMAIL }}
  ServiceAccountPrivateKey: ${{ secrets.SERVICEACCOUNTPRIVATEKEY }}

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v5
    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: 🚚 Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: 🛠️ Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: 🧪 Test
      run: dotnet test "${{ env.TESTING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --filter Category!=local
